CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
phone VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
registered_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
ADD COLUMN current_balance DECIMAL(10,2) NOT NULL DEFAULT 0.00;

CREATE TABLE transactions (
id INT AUTO_INCREMENT PRIMARY KEY,
type ENUM('credit','debit') NOT NULL,
amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
new_balance DECIMAL(10,2) NOT NULL,
transaction_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
remark VARCHAR(255)
);

ALTER TABLE transactions
ADD COLUMN user_id INT NOT NULL;